<a href="https://colab.research.google.com/github/nermienkh/Pytorch_From_Scratch/blob/main/pytorch_from_scratch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Pytorch-Wikipedia](https://https://en.wikipedia.org/wiki/PyTorch)
PyTorch is an open source machine learning framework based on the Torch library,used for applications such as computer vision and natural language processing, primarily developed by Meta AI

PyTorch provides two high-level features:


1.   Tensor computing (like NumPy) with strong acceleration via graphics processing units (GPU) 

2.   Deep neural networks built on a tape-based [automatic differentiation](https://www.youtube.com/watch?v=wG_nF1awSSY)  system






PyTorch defines a class called **Tensor** (torch.Tensor) to store and operate on homogeneous multidimensional rectangular arrays of numbers. PyTorch Tensors are similar to NumPy Arrays, **but can also be operated on a CUDA-capable NVIDIA GPU**

**Main Modules**



1.  *Autograd module:*
PyTorch uses a method called automatic differentiation. A recorder records what operations have performed, and then it replays it backward to compute the gradients. This method is especially powerful when building neural networks to save time on one epoch by calculating differentiation of the parameters at the forward pass.
2.  *Optim module:*
torch.optim is a module that implements various optimization algorithms used for building neural networks. Most of the commonly used methods are already supported, so there is no need to build them from scratch.
3. *nn module:*
PyTorch autograd makes it easy to define computational graphs and take gradients, but raw autograd can be a bit too low-level for defining complex neural networks. This is where the nn module can help. The nn module provides layers and tools to easily create a neural networks by just defining the layers of the network.


**low level programming**

In [1]:
#import the torch library 
import torch


In [3]:
#create  Tensor with values
new_tensor = torch.Tensor([[1, 2], [5, 6]])
new_tensor 

tensor([[1., 2.],
        [5., 6.]])

In [4]:
#create tensor with known size, random values	
empty_tensor = torch.Tensor(5, 3)
empty_tensor

tensor([[7.1591e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.1771e-43, 1.4153e-43, 1.5414e-43],
        [1.6115e-43, 1.5554e-43, 1.5975e-43],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])

In [13]:
#create tensor with uniform random values between -1 and 1
# 5 arrays, 3 rows, 2 columns	
uniform_tensor = torch.Tensor(5, 3,2).uniform_(-1, 1)
uniform_tensor

tensor([[[ 0.4078, -0.4047],
         [-0.4357,  0.3520],
         [-0.5049,  0.3194]],

        [[-0.1005, -0.4319],
         [ 0.1084,  0.5168],
         [-0.3252, -0.5553]],

        [[-0.7955,  0.4859],
         [ 0.8544,  0.5092],
         [-0.3965, -0.0679]],

        [[ 0.5830, -0.1366],
         [ 0.1959, -0.8244],
         [-0.3431,  0.1830]],

        [[-0.6088,  0.9731],
         [ 0.6043,  0.8911],
         [ 0.9469,  0.5910]]])

In [16]:
#create tensor with uniform distribution values between 0 and 1
rand_tensor = torch.rand(1, 3)
rand_tensor

tensor([[0.2558, 0.9478, 0.1159]])

In [17]:
#access elements in tensor 
#get value of second array second row second column ,0.5168
uniform_tensor[1][1][1]

tensor(0.5168)

In [18]:
#get the last array using the slicing 
#[-0.6088,  0.9731],
#[ 0.6043,  0.8911],
#[ 0.9469,  0.5910]]
uniform_tensor[-1,:,:]

tensor([[-0.6088,  0.9731],
        [ 0.6043,  0.8911],
        [ 0.9469,  0.5910]])

In [21]:
#get the diminsion and size of a tensor 
print(uniform_tensor.dim())
print(uniform_tensor.size())

3
torch.Size([5, 3, 2])


In [25]:
#reshape tensor, note the view function is immutable, you need to save the result in new object to keep it  
uniform_tensor.view(5,1,6)

tensor([[[ 0.4078, -0.4047, -0.4357,  0.3520, -0.5049,  0.3194]],

        [[-0.1005, -0.4319,  0.1084,  0.5168, -0.3252, -0.5553]],

        [[-0.7955,  0.4859,  0.8544,  0.5092, -0.3965, -0.0679]],

        [[ 0.5830, -0.1366,  0.1959, -0.8244, -0.3431,  0.1830]],

        [[-0.6088,  0.9731,  0.6043,  0.8911,  0.9469,  0.5910]]])

In [26]:
#summation of 2 tensors
x = torch.empty(5, 3)
y = torch.empty(5, 3)
x+y

tensor([[4.6002e-34, 0.0000e+00, 2.3694e-38],
        [2.3694e-38,        nan, 2.3694e-38],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [29]:
#transpose tensor
print(y)
print(y.t())
print(y.permute(-1,0))

tensor([[2.3001e-34, 0.0000e+00, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 3.6013e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[2.3001e-34, 2.3694e-38, 2.3694e-38, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.3694e-38, 3.6013e-43, 0.0000e+00, 0.0000e+00],
        [2.3694e-38, 2.3694e-38, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[2.3001e-34, 2.3694e-38, 2.3694e-38, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.3694e-38, 3.6013e-43, 0.0000e+00, 0.0000e+00],
        [2.3694e-38, 2.3694e-38, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [33]:
#matrix multiplication, sizes should be (m*n) * (n*m)
x=torch.Tensor(2,5)
y=torch.Tensor(5,2)
result=x.mm(y)
print(result.shape)

torch.Size([2, 2])


In [34]:
#move to GPU	
x = torch.randn(4, 4)
y = torch.randn(4, 4)
#check if GPU is Available
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device)
    y = y.to(device)  
    z = x + y
    print(z)

**High level programming**

In [36]:
#build Neural Network